-- MySQL Script generated by MySQL Workbench
-- Wed Dec 20 08:33:17 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rtsystems
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rtsystems
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rtsystems` DEFAULT CHARACTER SET utf8mb4 ;
USE `rtsystems` ;

-- -----------------------------------------------------
-- Table `rtsystems`.`cidade`
-- -----------------------------------------------------
-- CREATE TABLE IF NOT EXISTS `rtsystems`.`cidade` (
--   `id` INT(11) NOT NULL,
--   `nome` VARCHAR(120) NULL DEFAULT NULL,
--   `uf` INT(2) NULL DEFAULT NULL,
--   PRIMARY KEY (`id`))
-- ENGINE = MyISAM
-- DEFAULT CHARACTER SET = utf8
-- COMMENT = 'Municipios das Unidades Federativas';


-- -----------------------------------------------------
-- Table `rtsystems`.`estado`
-- -----------------------------------------------------
-- CREATE TABLE IF NOT EXISTS `rtsystems`.`estado` (
--   `id` INT(11) NOT NULL,
--   `nome` VARCHAR(75) NULL DEFAULT NULL,
--   `uf` VARCHAR(2) NULL DEFAULT NULL,
--   PRIMARY KEY (`id`))
-- ENGINE = MyISAM
-- DEFAULT CHARACTER SET = utf8
-- COMMENT = 'Unidades Federativas';


-- -----------------------------------------------------
-- Table `rtsystems`.`tabevents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rtsystems`.`tabevents` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `eventName` VARCHAR(80) NOT NULL,
  `eventDescription` VARCHAR(600) NOT NULL,
  `eventStart` DATETIME NOT NULL,
  `eventEnd` DATETIME NOT NULL,
  `eventCodTime` INT(11) NOT NULL,
  `eventVacancies` INT(11) NOT NULL,
  `eventPayment` FLOAT NOT NULL,
  `eventProfessional` INT(11) NOT NULL,
  `eventUF` INT(11) NOT NULL,
  `eventCodCidade` INT(11) NOT NULL,
  `eventGeoLocation` VARCHAR(20) NOT NULL,
  `eventRua` VARCHAR(150) NOT NULL,
  `eventRuaNumero` FLOAT NOT NULL,
  `eventLocation` VARCHAR(150) NULL DEFAULT NULL,
  `eventActive` INT(11) NOT NULL DEFAULT 1,
  `eventContractorId` INT(11) NOT NULL,
  `eventContractor` VARCHAR(100) NOT NULL,
  `eventContractorEmail` VARCHAR(100) NOT NULL,
  `eventContractorTel` VARCHAR(15) NOT NULL,
  `eventDTAR` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `rtsystems`.`tabinscricoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rtsystems`.`tabinscricoes` (
  `tabevents_id` INT(11) NOT NULL,
  `tabusers_cadID` INT(11) NOT NULL,
  `user_codigo` VARCHAR(11) NOT NULL,
  `inscricao_data` DATETIME NOT NULL,
  `inscricao_validate` INT(11) NOT NULL,
  PRIMARY KEY (`tabevents_id`, `tabusers_cadID`),
  INDEX `fk_tabevents_has_tabusers_tabusers1` (`tabusers_cadID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `rtsystems`.`tabusers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rtsystems`.`tabusers` (
  `cadID` INT(11) NOT NULL AUTO_INCREMENT,
  `cadName` VARCHAR(80) NOT NULL,
  `cadEmail` VARCHAR(100) NOT NULL,
  `cadPswd` VARCHAR(50) NOT NULL,
  `cadNick` VARCHAR(45) NOT NULL,
  `cadRG` VARCHAR(14) NOT NULL,
  `cadCPF` VARCHAR(11) NOT NULL,
  `cadDataNasc` DATE NOT NULL,
  `cadTelefone` VARCHAR(13) NOT NULL,
  `cadCelular` VARCHAR(14) NOT NULL,
  `cadCelularEm` VARCHAR(14) NULL DEFAULT NULL,
  `cadCodigo` VARCHAR(11) NOT NULL,
  `cadDataCod` DATE NOT NULL,
  `cadCep` VARCHAR(8) NOT NULL,
  `cadUf` INT(11) NOT NULL,
  `cadCidade` INT(11) NOT NULL,
  `cadLogradouro` VARCHAR(150) NOT NULL,
  `cadNumero` INT(11) NOT NULL,
  `cadComplemento` VARCHAR(50) NULL DEFAULT NULL,
  `cadValidate` INT(11) NOT NULL,
  PRIMARY KEY (`cadID`))
ENGINE = InnoDB
AUTO_INCREMENT = 38
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
